services:
  backend:
    build:
      context: ./backend
    container_name: meu-backend
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      # ESP_SERIAL_PORT: /dev/ttyUSB0  # ou ESP_IP para modo HTTP
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"

  frontend:
    build:
      context: ./myfrontend
    container_name: meu-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000

  postgres:
    image: postgres:15
    container_name: meu-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: